"""``xlsx`` renderer: one sheet per table, with a cover sheet. openpyxl, no formulas."""

from __future__ import annotations

import io
from datetime import date, datetime
from typing import TYPE_CHECKING, Any, ClassVar

from openpyxl import Workbook
from openpyxl.cell.cell import Cell
from openpyxl.styles import Font

from dsec_metrics.plugins.sdk.renderer import Renderer
from dsec_metrics.reports.tables import tables

if TYPE_CHECKING:
    from dsec_metrics.reports.data import ReportData

# Workbook properties are fixed so the same data gives the same file.
FIXED_TIME = datetime(2000, 1, 1)  # noqa: DTZ001 (xlsx stores naive times)


def _put(cell: Cell, value: Any) -> None:
    """Write a value. Strings are always stored as text, never as formulas, so a record
    starting with = or @ cannot run in a spreadsheet."""
    if isinstance(value, (list, tuple)):
        value = ", ".join(str(v) for v in value)
    elif isinstance(value, (date, datetime)):
        value = value.isoformat()
    cell.value = value
    if isinstance(value, str):
        cell.data_type = "s"


class XlsxRenderer(Renderer):
    """Report tables as an Excel workbook."""

    name = "xlsx"
    version = "1.0.0"
    media_types: ClassVar[dict[str, str]] = {
        "xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    }

    def render(self, data: ReportData) -> dict[str, bytes]:
        wb = Workbook()
        cover = wb.active
        if cover is None:  # pragma: no cover (a new workbook always has one sheet)
            cover = wb.create_sheet("Report")
        cover.title = "Report"
        rows = [
            ("Report", data.title),
            ("Type", data.request.report_type.value),
            ("Period start", data.request.period_start.isoformat()),
            ("Period end", data.request.period_end.isoformat()),
            ("Prepared for", data.request.prepared_for),
            ("Generated", data.generated_at.isoformat()),
            ("Generated by", data.generated_by),
            ("Signing key fingerprint", data.key_fingerprint),
            *((f"Count {status}", n) for status, n in data.summary.items()),
        ]
        for i, (label, value) in enumerate(rows, start=1):
            _put(cover.cell(row=i, column=1), label)
            _put(cover.cell(row=i, column=2), value)
            cover.cell(row=i, column=1).font = Font(bold=True)
        for table in tables(data):
            ws = wb.create_sheet(table.name[:31])
            for col, name in enumerate(table.columns, start=1):
                _put(ws.cell(row=1, column=col), name)
                ws.cell(row=1, column=col).font = Font(bold=True)
            for r, row in enumerate(table.rows, start=2):
                for col, value in enumerate(row, start=1):
                    _put(ws.cell(row=r, column=col), value)
            ws.freeze_panes = "A2"
        wb.properties.created = FIXED_TIME
        wb.properties.modified = FIXED_TIME
        wb.properties.creator = "dsec-metrics"
        buffer = io.BytesIO()
        wb.save(buffer)
        return {"report.xlsx": buffer.getvalue()}
